version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: bus_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: QuanLyXeBuyt
      MYSQL_USER: bususer
      MYSQL_PASSWORD: vinh
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - bus_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: bus_backend
    environment:
      NODE_ENV: production
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: bus_management
      DB_USER: bususer
      DB_PASSWORD: buspassword
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      JWT_REFRESH_SECRET: your-super-secret-refresh-key-change-in-production
      JWT_EXPIRES_IN: 1h
      JWT_REFRESH_EXPIRES_IN: 7d
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - bus_network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bus_frontend
    environment:
      VITE_API_URL: http://localhost:3000/api
      VITE_SOCKET_URL: http://localhost:3000
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - bus_network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  bus_network:
    driver: bridge